### PR TITLE
Proper file name for panelToolbar,pageContextMenu,toolsMenu,sidePanelOverlay modules

### PR DESCRIPTION
**Pull request by aliuk2012**
Sorry, there was a slight problem with the panelToolbar module commits but I got there in the end.

### CODE REVIEW

**Comment by fflorent** [comment]
That's a lot of commits, with reverts. Could you just [rebase them](http://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages) and do a `git push -f` to your repository (note that since it is your own repo, it is OK, but it is normally a really bad practice).

To rebase, you can use the `git rebase -i b6ca650` command (where b6ca650 is the hash of the parent of your first commit).

If you need assistance, I can help through IRC. Thanks in advance!

Florent

**Comment by aliuk2012** [comment]
Looking much better :-) Thank you

**Comment by fflorent** [comment]
The patch looks good.

Here is the list of files I listed which have camel-case names (the stroke ones are those that has been rename in this pull request):
* data/helloWorldContentScript.js
* <strike>lib/chrome/pageContextMenu.js</strike>
* <strike>lib/chrome/panelToolbar.js</strike>
* lib/chrome/sidePanelOverlay.js
* <strike>lib/chrome/toolsMenu.js</strike>
* lib/dom/domCache.js
* lib/dom/domPanel.js
* lib/dom/domProvider.js
* lib/dom/domSidePanel.js
* lib/dom/domTree.js
* lib/dom/textSearch.js
* lib/helloWorld/helloWorldPanel.js
* lib/helloWorld/helloWorldSidePanel1.js
* lib/helloWorld/helloWorldSidePanel2.js

@janodvarko Should we rename all of them?

Florent

**Comment by aliuk2012** [comment]
I'm happy to rename the rest (except for the helloWorld ones which I'm assuming will get removed)

**Comment by fflorent** [comment]
Eventually yes.

Florent

**Comment by aliuk2012** [comment]
Thats the last of the /lib/chrome files. I'll create a separate pull request for the /lib/dom files

**Comment by janodvarko** [comment]
> @janodvarko Should we rename all of them?

Yes

> I'm happy to rename the rest (except for the helloWorld ones which I'm assuming will get removed) 

Excellent! (please do in another pull)

Honza

**Pull request merged**
