### PR TITLE
#269 Hand cursor for Call Stack entries

### PR DESCRIPTION
**Pull request by aliuk2012**
Hopefully this is alright for the merge

### CODE REVIEW

**Comment by fflorent** [comment]
I have the hand-cursor when hovering the lines of an item of the call stack, except when I hover a text (the filename or the stack label). Do you see the same issue? (haven't investigated why yet)

Florent

**Comment by aliuk2012** [comment]
oh yes I get that as well. its being overwritten by global.css line 200. In this instance would it be alright to use !IMPORTANT

**Comment by aliuk2012** [comment]
There that fix should hopefully do it.

@fflorent thanks for your help and support with this one.

**Comment by fflorent** [comment]
All good. Thanks!

Florent

**Comment by janodvarko** [comment]
Works for me too, thanks!
Honza

**Pull request merged**
