### PR TITLE
Fix for issue 255 - Hiding the sidebar breaks the computed view

### PR DESCRIPTION
**Pull request by anurag90x**

### CODE REVIEW

**Comment by fflorent** [comment]
BTW, what is the commit of the regression? I am wondering why this line causes the issue

Florent

**Comment by anurag90x** [comment]
It's this one:

https://github.com/firebug/firebug.next/commit/741fc4cb381bdfef0678d8e56fbefb58f99ea1fc

Specifically the line returning null. Since, it returns null (even [] would cause this issue) the sidebar is hidden and for the computed view, browser/computed-view.js does not like it. There's basically a NPE there, that breaks everything.

**Comment by fflorent** [comment]
Thanks for the patch.

Hmm, `basePanel.js` is a global module, changing its code may also impacts other panels than inspector.
Also our tests are not covering everything enough to ensure it would not introduce a regression.

Your patch may be OK, that's just that I don't know what this line was used for. 
@janodvarko what do you think of this patch?

Florent

**Comment by anurag90x** [comment]
Yup, makes sense. I'm apprehensive too :smiley: 

Just a little more detail if it helps:

Before that commit the getSidePanels method returned [DOMSidePanel] so everything was fine. After it, null was returned as a result of which  

if (!sidePanels || !sidePanels.length) {
      this.sidebar.hide();
      return;
    }

got executed. Thing is, when doing the side panels for inspector, the computed view overlay breaks. There's an error on the devtools side , apparently at this line -

  let styles = this.styleWindow.getComputedStyle(this.styleDocument.documentElement);
 
styles becomes null and the following for loop complains and nothing is displayed. This only happens for computed view though.

**Comment by janodvarko** [comment]
A better solution committed at:
https://github.com/firebug/firebug.next/commit/97cfc2df7053222fa2e64123b10ece675d7d0e36

Honza

**Comment by anurag90x** [comment]
Saw the commit. Yup that's a nicer approach. Cool.

**Pull request closed without merging**
