### PR TITLE
 #367: Updated console and warning styles

### PR DESCRIPTION
**Pull request by bmdeveloper**
#367: 1. Updated background colour of console errors to #FFEBEB
2. Updated text colour of console errors to #FF0000
3. Updated background colour of console warnings to #FFFFC8

### CODE REVIEW

**Comment by fflorent** [comment]
Sounds OK to me. If you could just squash the two commits into one, that would be great.

To do so, if you use Linux/Mac OS/msysgit, enter these command lines:
````shell
git reset --soft HEAD^
git commit --amend --no-edit
git push -f
````

Note: don't use the `git push -f` option unless you use it for your own repository, of course ;).

If you have any question, you can ask me through IRC (for one hour).

Florent

**Comment by bmdeveloper** [comment]
Thanks, I have merged those 2 commits

**Comment by bmdeveloper** [comment]
@fflorent hi is everything OK with this

**Comment by fflorent** [comment]
Yep (sorry for the huge delay). @janodvarko Are you OK with this merge?

Florent

**Comment by janodvarko** [comment]
Please use  .theme-firebug prefix in the CSS selector

Honza

**Comment by bmdeveloper** [comment]
@fflorent @janodvarko Ok I have made that change

**Comment by janodvarko** [comment]
Thanks!

Honza

**Pull request merged**
