### PR TITLE
Bug #284. Fixed alignment between side panel toolbar and main panel toolbar.

### PR DESCRIPTION
**Pull request by bmdeveloper**
Bug #284. Fixed alignment between side panel toolbar and main panel toolbar.

### CODE REVIEW

**Comment by janodvarko** [comment]
The Style Editor is broken now (see the side panel in Style Editor panel).

Honza

**Comment by bmdeveloper** [comment]
I see will take a look

**Comment by bmdeveloper** [comment]
I have made an update

**Comment by janodvarko** [comment]
Looks good to me!

Honza

**Comment by janodvarko** [comment]
The Network side panel seems to be broken now.

issue288

Honza

**Comment by bmdeveloper** [comment]
@janodvarko I cannot seem to replicate the above issue. I am using Windows 8.1 and Firefox nightly version 38.0a1.

**Comment by janodvarko** [comment]
@bmdeveloper true, I can't reproduce that anymore. I am not sure why I had the problem.
Consider it fixed and I'll reopen if I see it again :-)

Honza

**Pull request merged**
