### PR TITLE
Adding Unit tests for Locale.$STRF

### PR DESCRIPTION
**Pull request by vdebroy**
Adding basic unit tests for Locale.$STRF which is called by Locale.$STRP.

### CODE REVIEW

**Comment by vdebroy** [comment]
Requesting a Pull for additional unit tests with respect to locale.

**Comment by janodvarko** [comment]
Looks great, thanks!

There are other areas that need unit tests, interested? :-)

Honza

**Comment by janodvarko** [comment]
Just some white spaces removed at:
https://github.com/firebug/firebug.next/commit/0e452201f317946f6f1f0f8157146ac54a3fdf0a

Honza

**Comment by vdebroy** [comment]
Absolutely :) I love Firebug and would love to contribute more unit tests/functionality to the best of my abilities.

**Comment by janodvarko** [comment]
What about a test for XHR logs displayed in the Console panel (we recently landed fix for issue #180)
This test would require some interaction with the Console panel UI and you can take a look at exiting tests....

Honz

**Comment by janodvarko** [comment]
I can create an issue report for you with detailed requirements...

Honza

**Comment by vdebroy** [comment]
Sure! That sounds like a great way for me to learn more and also familiarize myself with the code-base. If possible, could you please also direct me to a sample test (if there is one) that has to do with the console. Thank you!

- Vidroha

**Comment by janodvarko** [comment]
Excellent!

Here you go:https://github.com/firebug/firebug.next/issues/329

Honza

**Comment by janodvarko** [comment]
You can assign to you as soon as you accept the invitation I just sent.
Honza

**Comment by vdebroy** [comment]
Assigned it to myself :-). Thank you for the wonderful instructions!

**Pull request merged**
